### ISSUE TITLE
[Question] Is it possible to decode image's bitmap data ?

### ISSUE THREAD

**Issue by cancerberoSgx** [martamius/Exif.hx#3]
Just that, before trying it I would like to know if this library is capable to obtain the bitmap data in GRB bytes (or similar) so I can process the bitmap programatically. If so It would be awesome since https://github.com/HaxeFoundation/format/ doesn't support jpg read . If not I can contribute with a small note in the readme. Thanks

**Comment by JWambaugh** [comment]
I don’t maintain this anymore, but no, it only reads the exif metadata.

**Comment by cancerberoSgx** [comment]
thanks!
